["W/S.PITCH"]
prototype = "W/S.PITCH voice pitch"
short = "Set `voice` (s8) to `pitch` (s16V) in volts-per-octave"

["W/S.VEL"]
prototype = "W/S.VEL voice velocity"
short = "Strike the vactrol of `voice` (s8) at `velocity` (s16V) in volts"

["W/S.VOX"]
prototype = "W/S.VOX voice pitch velocity"
short = "Set `voice` (s8) to `pitch` (s16V) and strike the vactrol at `velocity` (s16V)"

["W/S.NOTE"]
prototype = "W/S.NOTE pitch velocity"
short = "Dynamically assign a voice, set to `pitch` (s16V), strike with `velocity` (s16V)"

["W/S.POLY"]
prototype = "W/S.POLY pitch velocity"
short = "As `W/S.NOTE` but across dual W/. Switches between primary and secondary units every 4 notes or until reset using `W/S.POLY.RESET`."

["W/S.POLY.RESET"]
prototype = "W/S.POLY.RESET"
short = "Resets `W/S.POLY` note count."

["W/S.AR.MODE"]
prototype = "W/S.AR.MODE is_ar"
short = "In attack-release mode, all notes are `plucked` and no `release` is required"

["W/S.LPG.TIME"]
prototype = "W/S.LPG.TIME time"
short = "Vactrol `time` (s16V) constant. -5=drones, 0=vtl5c3, 5=blits"

["W/S.LPG.SYM"]
prototype = "W/S.LPG.SYM symmetry"
short = "Vactrol attack-release ratio. -5=fastest attack, 5=long swells (s16V)"

["W/S.CURVE"]
prototype = "W/S.CURVE curve"
short = "Cross-fade waveforms: -5=square, 0=triangle, 5=sine (s16V)"

["W/S.RAMP"]
prototype = "W/S.RAMP ramp"
short = "Waveform symmetry: -5=rampwave, 0=triangle, 5=sawtooth (NB: affects FM tone)"

["W/S.FM.INDEX"]
prototype = "W/S.FM.INDEX index"
short = "Amount of FM modulation. -5=negative, 0=minimum, 5=maximum (s16V)"

["W/S.FM.RATIO"]
prototype = "W/S.FM.RATIO num den"
short = "Ratio of the FM modulator to the carrier. floating point values up to 20.0 supported (s16V)"

["W/S.FM.ENV"]
prototype = "W/S.FM.ENV amount"
short = "Amount of vactrol envelope applied to FM index, -5 to +5 (s16V)"

["W/S.PATCH"]  
prototype = "W/S.PATCH jack param"
short = "Patch a hardware `jack` (s8) to a `param` (s8) destination"

["W/S.VOICES"]
prototype = "W/S.VOICES count"
short = "Set number of polyphonic voices to allocate. use 0 for unison mode (s8)"